# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="mine_and_blade"
version="${file.jarVersion}"
displayName="Mine & Blade"
credits="The Forge dev team"
authors="Rastersaurus Rex"
description='''
Example mod that uses Kotlin for Forge.
'''
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
